config/routes.rb
Rails.application.routes.draw do
  root 'todo_lists#index'
  resources :todo_lists do
    resources :todo_items
  end

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list
  validates :name, presence: true
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: [ :update, :destroy]
  before_action :set_todo_list

  def index
    @todo_items = @todo_list.todo_items.all
    @todo_item = @todo_items.new
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    @todo_items = @todo_list.todo_items.all
    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to todo_list_todo_items_path(@todo_list)}
      else
        format.html { render :index}
        format.json { render json: @todo_item.errors}
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to todo_list_todo_items_path(@todo_list)}
        format.json { respond_with_bip(@todo_item) }
      else
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
        format.json { respond_with_bip(@todo_item) }
      end
    end
  end

  def destroy
    @todo_item.destroy
    respond_to do |format|
      format.html { redirect_to todo_list_todo_items_path(@todo_list)}
      format.json { head :no_content }
    end
  end

  private
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def todo_item_params
      params.require(:todo_item).permit(:name, :todo_list_id, :completed)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [ :update, :destroy]

  def index
    @todo_lists = TodoList.all
    @todo_list = TodoList.new
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_lists = TodoList.all
    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to todo_lists_path}
      else
        format.html { render :index }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to todo_lists_path}
        format.json { respond_with_bip(@todo_list) }
      else
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
        format.json { respond_with_bip(@todo_list) }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url}
      format.json { head :no_content }
    end
  end

  private
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for [@todo_list, @todo_item] do |f| %>
  <% if @todo_item.errors.any? %>
    <div class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span></button>

      <% @todo_item.errors.full_messages.each do |message| %>
          <%= message %>
      <% end %>
    </div>
  <% end %>
  <div class="input-group">
    <%= f.text_field :name, :placeholder => "Add Item...",class: 'form-control'%>

    <span class="input-group-btn">
        <%= f.submit "Add", class: 'btn btn-default'%>
    </span>
  </div>
<% end %>

app/views/todo_items/index.html.erb
<div class="panel panel-default center">
  <div class="panel-heading">
    <h1><%= best_in_place @todo_list, :name, :type => :input %></h1>
  </div>
  <div class="panel-body">
    <%= render partial: "form" %>
  </div>
  <ul class="list-group">
        <% @todo_items.each do |todo_item| %>
            <li class="list-group-item">
                <%= best_in_place todo_item, :completed, :type => :checkbox, :path => todo_list_todo_item_path(@todo_list, todo_item), :collection => [raw("<span class='glyphicon glyphicon-unchecked make-bigger'></span>"), raw("<span class='glyphicon glyphicon-check make-bigger'></span>")]%>
                <%= best_in_place todo_item, :name, :type => :input, :path => todo_list_todo_item_path(@todo_list, todo_item)%>
                <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, todo_list_todo_item_path(@todo_list, todo_item), method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-right"%>
            </li>
        <% end %>
    </ul>
  <div class="panel-footer">
    <%= link_to '<span class="glyphicon glyphicon-circle-arrow-left make-bigger"></span>'.html_safe, todo_lists_path %>
  </div>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
        <div class="alert alert-danger alert-dismissible">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span></button>
      <% @todo_list.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    </div>
  <% end %>

  <div class="input-group">
    <%= f.text_field :name, :placeholder => "Add List...",class: 'form-control'%>
    <span class="input-group-btn">
        <%= f.submit "Add", class: 'btn btn-default'%>
    </span>
  </div>
<% end %>

app/views/todo_lists/index.html.erb
<div class="panel panel-default center">
  <div class="panel-heading">
    <h1>Todo</h1>
  </div>
  <div class="panel-body">
    <%= render partial: "form" %>
  </div>
    <ul class="list-group">
        <% @todo_lists.each do |todo_list| %>
          <li class="list-group-item">
            <%= link_to todo_list.name, todo_list_todo_items_path(todo_list) %>
            <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe, todo_list, method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-right space" %>
            <% if todo_list.todo_items.where(completed: [false, nil]).count > 0 %>
                <span class="badge pull-right">
                  <%= todo_list.todo_items.where(completed: [false, nil]).count%>
                </span>
            <% end %>
          </li>
        <% end %>
    </ul>
</div>